apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: {{ .Values.DB_HOST | b64enc | quote }}
  DB_ROOT_USERNAME: {{ .Values.DB_ROOT_USERNAME | b64enc | quote }}
  DB_ROOT_PASSWORD: {{ .Values.DB_ROOT_PASSWORD | b64enc | quote }}
  {{- range $appName, $values := .Values.databases }}
  {{ printf "%s_%s" $appName "DB_NAME"}}: {{$values.DB_NAME | b64enc | quote}}
  {{ printf "%s_%s" $appName "DB_USERNAME"}}: {{$values.USERNAME | b64enc | quote}}
  {{ printf "%s_%s" $appName "DB_PASSWORD"}}: {{$values.PASSWORD | b64enc | quote}}
  {{- end }}
