name: Build and Publish
on:
  push:
    branches: [ BAH-1809 ]

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify app version
        run: |
          CHART_VERSION=$(yq .version Chart.yaml)
          if [ $(git tag -l "$CHART_VERSION") ]; then 
            echo "Chart version $CHART_VERSION already released. Please update chart version in Chart.yaml to represent next major/minor/patch increment"
            exit 1
          else
            echo "setting artifact version to $(echo $CHART_VERSION-${{github.run_number}})"
            echo "ARTIFACT_VERSION=$(echo $CHART_VERSION-${{github.run_number}})" >> $GITHUB_ENV
          fi
      - name: Update Version
        run: |
            yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' Chart.yaml
      - name: Helm Lint
        run: helm lint .

      - name: Helm Package
        run: helm package .
      
      - name: Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: Bahmni/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Copy Helm Archive
        run: mkdir -p helm-charts/db-setup/ && cp db-setup-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/db-setup/

      - name: Helm Index
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .

      - name: Commit and Push Chart Repository
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of db-setup-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages

